### ISSUE TITLE
Interrupt handlers not ran

### ISSUE THREAD

**Issue by makerimages** [makerimages/OSZin#12]
There's debug printouts in them, but they never get ran...

/cc @exetwezz

**Comment by ghost** [comment]
@makerimages, Please, [read this](http://www.maultech.com/chrislott/resources/cstyle/). Your code is unreadable. Also, why do you use `reinprepret_cast<>` instead of just using `(type) var` (I don't know C++, actually)?

I've removed the build system you use, removed the libc you use, and copied the [musl libc](http://www.musl-libc.org/) I'm [porting myself](https://github.com/exetwezz/jk1) to `/libc/`. Also, I'm currently writing Makefiles for the kernel and the whole project (kernel + libc). Sorry, it is taken from my own kernel (MIT License), and, if you don't mind, you can use that to build your kernel (I can't say OS, because there are no any programs). At the moment, the directories structure looks this (I'll update that if it changes):

```
Last updated: 14:52 GMT
.
├── kernel
│   ├── arch
│   │   └── ia32
│   │       └── modules
│   ├── include
│   │   └── modules
│   └── src
│       └── modules
├── libc
│   ├── arch
│   │   └── ia32
│   │       └── bits
│   ├── include
│   │   └── bits -> ../arch/ia32/bits
│   ├── src
│   │   ├── ctype
│   │   ├── internal
│   │   └── string
│   └── tools
└── sysroot
    ├── boot
    │   └── grub
    └── usr
        ├── include
        │   └── bits
        └── lib

26 directories

TODO: move header files of arch-dependent modules from include/modules/ to include/arch/ia32/modules/.
```

**Comment by ghost** [comment]
@makerimages, also, you need to add mask and unmask IRQ functions to the PIC class.

**Comment by ghost** [comment]
@makerimages, why did you remove ISRs from interrupt-entry.s? I was talking about [IDT.cpp](https://github.com/makerimages/OSZin/blob/master/src/OSZin/modules/IDT.cpp#L106).

**Comment by ghost** [comment]
@makerimages, so I got it working.

![oszin_irq0_works](https://cloud.githubusercontent.com/assets/5584865/6983747/4d0c7000-da2a-11e4-8beb-625d66ef9a95.png)

Don't pay attention to the lag. It was caused because it works very fast.

_removed text that doesn't make sense_

Upd: GTG, [download this](https://yadi.sk/d/PufV4ImpfjR3j). Read CHANGES.txt.

**Comment by makerimages** [comment]
@exetwezz Wow, awesome! Thank's a lot. Do you have/will have a fork of this I could merge here? Would be nice to track this change in GH. The main reason for `reinterpret_cast` I believe was, that `(type) var` is C style casting. Bochs is throwing up a weird error of some sort, gotta figure that out.

**Comment by ghost** [comment]
@makerimages, yup, it's C-style.

What error? Gonna check it out. (I don't get any warning, seems like it's because of difference in versions of Bochs we use.)

**Comment by makerimages** [comment]
`bochs-bin: symbol lookup error: /usr/lib/bochs/plugins/libbx_x.so: undefined symbol: XpmCreatePixmapFromData`

**Comment by ghost** [comment]
@makerimages, Ah... Add

```
display_library: sdl
```

to .bochsrc or whatever Bochs automatically loads (you may need `bochs-sdl` package to be installed).

**Comment by makerimages** [comment]
Rather: uncomment it.

**Comment by makerimages** [comment]
Works after that.

**Comment by ghost** [comment]
@makerimages, read CHANGES.txt and the sources after that. I've put useful info for you there.

**Comment by makerimages** [comment]
@exetwezz Indeed.

**Comment by ghost** [comment]
@makerimages Sorry, but I'm not so familiar with git. I'm currently [reading the book](http://www.git-scm.com/book/en/v2), and think I can do this tomorrow.

Hmm.. Can I just fork your repo, commit changes and create a PR to make you available to merge?

**Comment by makerimages** [comment]
Perfect! Git is really not that hard, don't worry :wink:. Also, is the commented out part in IDT.cc still functional? If not, what is the reccommended new way to declare handlers?

**Comment by makerimages** [comment]
@exetwezz Regarding your edit, yes you can!

**Comment by ghost** [comment]
@makerimages, so, the pull request #13.

The best way I know is to have arrays of pointers to handlers of exceptions and IRQs. For exceptions, the array has 32 elements. For IRQs, the array has 16 elements. And whenever an interrupt occurs, you, in your C handler of an interrupt (that is called from an ISR), determine, is it an exception or an IRQ. In the former case, you get the pointer to the handler of occurred exception from the array of handlers of exceptions. In the latter case, you do the same, but from the array of handlers of IRQs.

Also, you can have only two functions: to set the exception handler, and to set the IRQ handler. You don't need to have unset function, because you can just pass NULL as the pointer to a handler (so when your C handler looks for a custom handler, it checks is it NULL, and if it is, halts the computer with the message that handler not found, or does another thing that you want).

**Comment by makerimages** [comment]
Ok, so an array of function pointers.. I'll write that down.

**Comment by makerimages** [comment]
@exetwezz tried sth like this in Interrupt.cc

```
typedef void (*func_ptr_t)();
func_ptr_t arr[32];
```

upon later trying to set one manually `arr[0] = someFunc` gives arr does not name a type... I'm most likely missing sth simple, cuz I'm semi-ill and can't think very well.

**Comment by ghost** [comment]
`void *` is enough, _for an array_.

**Comment by makerimages** [comment]
@exetwezz Yeah, missed this comment when I implemented them. Current version works fine.
