### ISSUE TITLE
tm.kputsf() not working reliably.

### ISSUE THREAD

**Issue by makerimages** [makerimages/OSZin#14]
Lines like `tm.kputsf("Region, address %x size %d KB, type FREE.\n",mmap->addr,mmap->len/1024);` Make the `%d` be 0. However, elf stacktrace printout works fine with 2 arguments...

**Comment by makerimages** [comment]
Could be an overflow of sth..

**Comment by ghost** [comment]
@makerimages, are you sure that `mmap->len / 1024` is not `0`?

I've a memory map with length 0x90, and if I divided it by 1024, I'd get 0.

The `itoa()` and `itoa_s()` functions are working correctly [for the past two months](https://github.com/exetwezz/Basic_OS/commits/7046fd5adb6f7d760ba558e975adc02e21609fb3/kernel/src/basic/string.c), and won't fail further.

However, I doubt whether there could be a buffer overflow. I've a [buffer with the size of 33 bytes](https://github.com/exetwezz/jk1/commit/460f242ce87782ba9fc7f77ef1e41b511a1783f0) (as you): 32 bytes for a number, and 1 byte for the zero byte. 32 bytes are enough to store a converted to a string 32-bit number (in the binary, octal, decimal, or hexadecimal form, doesn't matter): 11111111 11111111 1111111 1111111 => 37777777777 => 4294967295 => FFFFFFFF (as you can see, the size of the buffer needed to store the number reduces across different number systems, and since binary is the smallest number system, and it fits into our 32-bit buffer, then any other number system will fit).

But if you want to print 64-bit (or 128-bit, etc.) numbers, then you need a larger buffer (for 64-bit it is 64+1 bytes, for 128-bit it is 128+1 bytes, etc.).

**Comment by makerimages** [comment]
@exetwezz, absolutely positively sure that it is not 0.  The weird thing is - it seems to only occurr on the combination of `%sth` and `%d`. Remove the  `%sth`  and the size prints out fine...

**Comment by ghost** [comment]
@makerimages, I'm not sure this may cause any problems, but could you try to move the contents of `TextMode::kputsfImpl()` to `TextMode::kputsf()`?

**Comment by makerimages** [comment]
@exetwezz, no difference.

**Comment by ghost** [comment]
@makerimages, this isn't a problem with `itoa()` — the argument is incorrect itself.

Did it work correctly before merging the pull request #13?

**Comment by ghost** [comment]
So, damn, my kernel has this issue too.

**Comment by makerimages** [comment]
Hah! You learn something new every day... Guess nothing we could do?

**Comment by makerimages** [comment]
@exetwezz The specific print was added after merging PR #13. So no way to tell for sure. Other kputsf's are still working fine, though.. (hex and decimal only? decimal as second only?)

**Comment by ghost** [comment]
@makerimages, so, it's definitely sth. with stack. Trying to print large number (> 32-bit, e.g. 64-bit) before another number crashes things, but they still work.

**Comment by ghost** [comment]
@makerimages, actually I'm currently reading the ARM ARM, so, you're true.

**Comment by ghost** [comment]
@makerimages, so yeah! I found the issue.
See this: https://github.com/makerimages/OSZin/blob/master/kernel/include/Multiboot.h#L199.

**Comment by ghost** [comment]
You pass the 64-bit value to kputsf(), but kputsf() assumes it 32-bit. You need either:
1. make kputsf() supporting printing 64-bit value,
2. or just create a 32-bit value containing the low 32 bits of the 64-bit address, and print that instead of the 64-bit value.

**Comment by makerimages** [comment]
`va_arg()` gives 64 bit outputs?

**Comment by ghost** [comment]
`va_arg (list, int)` gives 32-bit, but the argument is actually 64-bit, so it takes the low 32 bits of the argument; and when it is called again, it then gives the upper 32 bits of the argument. In your case, the upper 32 bits of the 64-bit address were zero, so it printed zero the second time.

**Comment by makerimages** [comment]
What makes it 64bit then?
Some varg stupidity?

**Comment by ghost** [comment]
Press the above link.

**Comment by makerimages** [comment]
What link?

**Comment by ghost** [comment]
Update this page, I edit comments after posting :)

**Comment by makerimages** [comment]
Thanks again, @exetwezz!
