### ISSUE TITLE
Unmask error isr's

### ISSUE THREAD

**Issue by makerimages** [makerimages/OSZin#35]
@exetwezz You know the PIC code a bit better, what trick do I need to pull off to get the error interrupts to fire?

**Comment by ghost** [comment]
Hello, @makerimages!

I've inspected your `cpu/interrupt.c` and its `isr_handler` function which gets called in a low-level exception handler checks whether the exception has a custom handler. Divide-by-zero exception, as I've tested, doesn't have one, for example.

So, you need to either add a custom handler for every exception, or just write a generic code for each exception that doesn't have a custom handler which, for example, prints the exception number and its name and finally halts, because it's generic and can't solve a problem that caused the exception.

To test, I've used modified `boot.s`:

``` diff
diff --git a/kernel/boot.s b/kernel/boot.s
index 484e002..162312d 100644
--- a/kernel/boot.s
+++ b/kernel/boot.s
@@ -49,6 +49,13 @@ _start:

        call kernel_main

+    # Test exceptions (actually, only one, but they should be configured
+    # the same way).
+    movw $93, %ax                       # dividend (random number)
+    movw $0, %bx                        # divisor
+    div %bx                             # divide %ax by %bx
+    # Above should cause an exception.
+
 .Lhang:
        jmp .Lhang
```

**Comment by makerimages** [comment]
Hey, @exetwezz, also see `idt.c` I add the Exception handlers there.

**Comment by ghost** [comment]
@makerimages well, the problem is that you subtract 32 from the exception number.

P.S. add static libraries to `.gitignore`

**Comment by makerimages** [comment]
@exetwezz setting isr0 callback to 0+32 doesn't do a thing..

**Comment by ghost** [comment]
@makerimages why 0+32? Why do

> you subtract 32 from the exception number

in the `isr_handler`?
